version: '3.9'
services:
  ssh.cyrhades.fr:
    build: ./.docker/ssh
  webssh.cyrhades.fr:
    build: ./.docker/webssh
    ports:
      - ${PORT}:8888
  blind-date.cyrhades.fr:
    image: anssi/fcsc2021-pwn-blind-date:latest
    ports:
      - ${PORT_SSH}:4000
